---
title: "Game of Thrones - Summary by Season"
author: "Danfeng Zhang"
date: today
output:
  pdf_document:
    fig-align: center
execute:
  enabled: true
  echo: false
  engine: jupyter
---

```{python}
#| tags: [parameters]
season = 1
```

```{python}
import pandas as pd
import matplotlib.pyplot as plt
current_season = season
df = pd.read_csv(f"../Data/season_{current_season}.csv")

viewers = df['viewers']
episodes = df['no_season']
titles = df['title']
directors = df['directed_by']
descriptions = df['description']
```

# Game of Thrones - Season `{python} current_season` Summary in Numbers

### __(*Warning:* spoilers ahead)__

***

### Overview

(From the [Wikipedia](https://en.wikipedia.org/wiki/Game_of_Thrones#Premise)) Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones.

Set on the fictional continents of Westeros and Essos, Game of Thrones has a large ensemble cast and follows several story arcs throughout the course of the show. A major arc concerns the Iron Throne of the Seven Kingdoms of Westeros through a web of political conflicts among the noble families either vying to claim the throne or fighting for independence from it. Another focuses on the last descendant of the realm's deposed ruling dynasty, who has been exiled to Essos and is plotting a return to the throne. A third story arc follows the Night's Watch, a military order defending the realm against threats from the North.

***

### Season `{python} current_season` Summary

Below you can see how the viewership evolved across episodes:

Season `{python} current_season` of Game of Thrones consisted of `{python} len(viewers)` episodes that aired between:

- First Episode Premiere: `{python} df['premiere_date'].iloc[0].replace('\xa0', ' ').strip().capitalize()`
- Last Episode Premiere: `{python} df['premiere_date'].iloc[-1].replace('\xa0', ' ').strip().capitalize()`

The average first-day TV viewership was `{python} viewers.mean().round(2)` million viewers in the US.

The most popular episode was `{python} titles[viewers.idxmax()]`, which attracted `{python} viewers.max()` million viewers. in which:

> `{python} descriptions[viewers.idxmax()]`

***

You can see how the viewership of the episodes changed in Figure 1.

```{python}
#| label: fig-polar
plt.figure(figsize=(10, 6))
plt.plot(episodes, viewers, marker='o', color='red', linewidth=2)
plt.xlabel("Episode Number")
plt.ylabel("First-Day Viewers (Millions)")
plt.title(f"Viewership Trend - Season {current_season}")
plt.grid(True)
plt.xticks(episodes)
plt.show()
```

***

Finally, the episodes with the above-average viewership were:

```{python}
#| echo: false
#| results: asis
from IPython.display import Markdown, display
avg = df['viewers'].mean()
above_avg = df[df['viewers'] > avg]

lines = []
# lines.append("Finally, the episodes with the above-average viewership were:\n")
lines.append("| No. in season | Title  | Directed by  | Viewers |")
lines.append("|:--------------|:------:|:------------:|--------:|")

for idx, row in above_avg.iterrows():
    lines.append(f"| {row['no_season']} | {row['title']} | {row['directed_by']} | {row['viewers']} |")

display(Markdown("\n".join(lines)))
```
