<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>assignment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Assignment_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment_files/libs/quarto-html/quarto-syntax-highlighting-de070a7b0ab54f8780927367ac907214.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div class="sourceCode" id="cb1"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span><span class="kw">:</span><span class="at"> </span><span class="st">'Meta-Analysis of Children</span><span class="sc">''</span><span class="st">s Toy Preferences'</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">author</span><span class="kw">:</span><span class="at"> </span><span class="st">'Your Name'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">date</span><span class="kw">:</span><span class="at"> </span><span class="st">"2025-05-24"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span><span class="kw">:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">html</span><span class="kw">:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">theme</span><span class="kw">:</span><span class="at"> lumen</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">toc</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">toc_float</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">title-block-banner</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">execute</span><span class="kw">:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">echo</span><span class="kw">:</span><span class="at"> fenced</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Update the path if necessary to match your project structure</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/metaanalysis_data.xlsx"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View structure and first rows</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 28
  Study            `Female authors` `Male authors` `Age (months)` N_boys N_girls
  &lt;chr&gt;                       &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 Alexander &amp; Sae…                2              0           19.5     47      47
2 Arthur (2014)                   1              0           19       22      18
3 Berenbaum &amp; Hin…                2              0           65.8     18      18
4 Berenbaum &amp; Sny…                2              0           93.1     19      19
5 Doering et al (…                1              3           87       15      15
6 Idle et al. (19…                2              1           46       10      10
# ℹ 22 more variables: Mean_boys_play_male &lt;dbl&gt;, SD_boys_play_male &lt;dbl&gt;,
#   Mean_girls_play_male &lt;dbl&gt;, SD_girls_play_male &lt;dbl&gt;,
#   Mean_boys_play_female &lt;dbl&gt;, SD_boys_play_female &lt;dbl&gt;,
#   Mean_girls_play_female &lt;dbl&gt;, SD_girls_play_female &lt;dbl&gt;,
#   `Neutral toys` &lt;dbl&gt;, Year &lt;dbl&gt;, `Parent present` &lt;dbl&gt;, Setting &lt;dbl&gt;,
#   Country &lt;dbl&gt;, `Case definition adequate` &lt;chr&gt;,
#   `Representativeness of cases` &lt;chr&gt;, `Selection of controls` &lt;chr&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [27 × 28] (S3: tbl_df/tbl/data.frame)
 $ Study                                    : chr [1:27] "Alexander &amp; Saenz (2012)" "Arthur (2014)" "Berenbaum &amp; Hines (1992)" "Berenbaum &amp; Snyder (1995)" ...
 $ Female authors                           : num [1:27] 2 1 2 2 1 2 5 2 3 3 ...
 $ Male authors                             : num [1:27] 0 0 0 0 3 1 1 0 3 3 ...
 $ Age (months)                             : num [1:27] 19.5 19 65.8 93.1 87 ...
 $ N_boys                                   : num [1:27] 47 22 18 19 15 10 21 38 12 25 ...
 $ N_girls                                  : num [1:27] 47 18 18 19 15 10 21 38 12 25 ...
 $ Mean_boys_play_male                      : num [1:27] 439 148 325 484 260 ...
 $ SD_boys_play_male                        : num [1:27] 166.1 105 270.2 141.3 67.7 ...
 $ Mean_girls_play_male                     : num [1:27] 248.6 54 135.1 202.5 98.4 ...
 $ SD_girls_play_male                       : num [1:27] 161 53 202 168 101 ...
 $ Mean_boys_play_female                    : num [1:27] 377.3 126 33.5 26.4 7.2 ...
 $ SD_boys_play_female                      : num [1:27] 170.9 67 69.5 92 21.5 ...
 $ Mean_girls_play_female                   : num [1:27] 539 244 248 265 145 ...
 $ SD_girls_play_female                     : num [1:27] 214 54 246 241 110 ...
 $ Neutral toys                             : num [1:27] 1 0 1 1 1 1 1 1 1 1 ...
 $ Year                                     : num [1:27] 2012 2014 1992 1995 1989 ...
 $ Parent present                           : num [1:27] 3 2 2 2 1 3 2 1 3 3 ...
 $ Setting                                  : num [1:27] 2 2 2 1 2 3 2 1 2 2 ...
 $ Country                                  : num [1:27] 0.256 0.28 0.252 0.252 0.141 0.141 0.248 NA 0.228 0.228 ...
 $ Case definition adequate                 : chr [1:27] "*" "*" "X" "*" ...
 $ Representativeness of cases              : chr [1:27] "*" "X" "*" "X" ...
 $ Selection of controls                    : chr [1:27] "X" "X" "*" "*" ...
 $ Parental opinion                         : chr [1:27] "X" "X" "*" "*" ...
 $ Comparability of both groups             : chr [1:27] "*" "**" "*" "*" ...
 $ Ascertainment of behaviour               : chr [1:27] "*" "*" "*" "*" ...
 $ Same ascertainment method for both groups: chr [1:27] "*" "*" "*" "*" ...
 $ Non‐response rate                        : chr [1:27] "X" "*" "X" "*" ...
 $ NOS score                                : num [1:27] 5 6 6 7 6 8 7 6 7 7 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute effect sizes (Hedges' g) and variances for male-typed toys</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>effects_male <span class="ot">&lt;-</span> <span class="fu">escalc</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="st">"SMD"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1i =</span> Mean_boys_play_male, <span class="at">sd1i =</span> SD_boys_play_male, <span class="at">n1i =</span> N_boys,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">m2i =</span> Mean_girls_play_male, <span class="at">sd2i =</span> SD_girls_play_male, <span class="at">n2i =</span> N_girls,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data, <span class="at">vtype =</span> <span class="st">"UB"</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Attach to main dataset</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">yi_m =</span> effects_male<span class="sc">$</span>yi,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">vi_m =</span> effects_male<span class="sc">$</span>vi</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute effect sizes for female-typed toys</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>effects_female <span class="ot">&lt;-</span> <span class="fu">escalc</span>(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="st">"SMD"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1i =</span> Mean_boys_play_female, <span class="at">sd1i =</span> SD_boys_play_female, <span class="at">n1i =</span> N_boys,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">m2i =</span> Mean_girls_play_female, <span class="at">sd2i =</span> SD_girls_play_female, <span class="at">n2i =</span> N_girls,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data, <span class="at">vtype =</span> <span class="st">"UB"</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Attach to main dataset</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">yi_f =</span> effects_female<span class="sc">$</span>yi,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">vi_f =</span> effects_female<span class="sc">$</span>vi</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Random-effects pooling via REML</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>res_male <span class="ot">&lt;-</span> <span class="fu">rma</span>(yi_m, vi_m, <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>res_female <span class="ot">&lt;-</span> <span class="fu">rma</span>(yi_f, vi_f, <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Show model summaries</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>res_male</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 27; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.2415 (SE = 0.0943)
tau (square root of estimated tau^2 value):      0.4914
I^2 (total heterogeneity / total variability):   75.67%
H^2 (total variability / sampling variability):  4.11

Test for Heterogeneity:
Q(df = 26) = 90.0510, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  1.0109  0.1130  8.9427  &lt;.0001  0.7893  1.2324  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>res_female</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 27; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.2513 (SE = 0.0963)
tau (square root of estimated tau^2 value):      0.5013
I^2 (total heterogeneity / total variability):   76.69%
H^2 (total variability / sampling variability):  4.29

Test for Heterogeneity:
Q(df = 26) = 95.4681, p-val &lt; .0001

Model Results:

estimate      se     zval    pval    ci.lb    ci.ub      
 -0.8967  0.1140  -7.8671  &lt;.0001  -1.1201  -0.6733  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Funnel plot &amp; Egger's test for small-study effects</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(res_male, <span class="at">main =</span> <span class="st">"Funnel Plot: Male-Typed Toys"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment_files/figure-html/funnel-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regtest</span>(res_male)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Test for Funnel Plot Asymmetry

Model:     mixed-effects meta-regression model
Predictor: standard error

Test for Funnel Plot Asymmetry: z =  4.8720, p &lt; .0001
Limit Estimate (as sei -&gt; 0):   b = -0.2752 (CI: -0.7954, 0.2450)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(res_female, <span class="at">main =</span> <span class="st">"Funnel Plot: Female-Typed Toys"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment_files/figure-html/funnel-plots-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regtest</span>(res_female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Test for Funnel Plot Asymmetry

Model:     mixed-effects meta-regression model
Predictor: standard error

Test for Funnel Plot Asymmetry: z = -3.2961, p = 0.0010
Limit Estimate (as sei -&gt; 0):   b =  0.1815 (CI: -0.4750, 0.8379)</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing moderators: neutral toy inclusion, parental presence, setting, country index, quality</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>res_male_mod <span class="ot">&lt;-</span> <span class="fu">rma</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  yi_m, vi_m,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mods =</span> <span class="sc">~</span> <span class="st">`</span><span class="at">Neutral toys</span><span class="st">`</span> <span class="sc">+</span> <span class="fu">factor</span>(<span class="st">`</span><span class="at">Parent present</span><span class="st">`</span>) <span class="sc">+</span> <span class="fu">factor</span>(Setting) <span class="sc">+</span> Country <span class="sc">+</span> <span class="st">`</span><span class="at">NOS score</span><span class="st">`</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"REML"</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 1 study with NAs omitted from model fitting.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>res_female_mod <span class="ot">&lt;-</span> <span class="fu">rma</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  yi_f, vi_f,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mods =</span> <span class="sc">~</span> <span class="st">`</span><span class="at">Neutral toys</span><span class="st">`</span> <span class="sc">+</span> <span class="fu">factor</span>(<span class="st">`</span><span class="at">Parent present</span><span class="st">`</span>) <span class="sc">+</span> <span class="fu">factor</span>(Setting) <span class="sc">+</span> Country <span class="sc">+</span> <span class="st">`</span><span class="at">NOS score</span><span class="st">`</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"REML"</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 1 study with NAs omitted from model fitting.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summaries of meta-regressions</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_male_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 26; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
-19.1896   38.3792   56.3792   64.3925   78.8792   

tau^2 (estimated amount of residual heterogeneity):     0.3232 (SE = 0.1430)
tau (square root of estimated tau^2 value):             0.5685
I^2 (residual heterogeneity / unaccounted variability): 79.28%
H^2 (unaccounted variability / sampling variability):   4.83
R^2 (amount of heterogeneity accounted for):            0.00%

Test for Residual Heterogeneity:
QE(df = 18) = 67.8142, p-val &lt; .0001

Test of Moderators (coefficients 2:8):
QM(df = 7) = 3.1263, p-val = 0.8731

Model Results:

                           estimate      se     zval    pval    ci.lb   ci.ub 
intrcpt                      1.2767  1.9280   0.6622  0.5079  -2.5021  5.0555 
`Neutral toys`              -0.1984  0.6171  -0.3215  0.7478  -1.4079  1.0111 
factor(`Parent present`)2   -0.3916  0.4659  -0.8406  0.4006  -1.3048  0.5215 
factor(`Parent present`)3   -0.3188  0.4734  -0.6734  0.5007  -1.2466  0.6091 
factor(Setting)2             0.3553  0.3944   0.9010  0.3676  -0.4176  1.1283 
factor(Setting)3             0.3335  0.6838   0.4877  0.6258  -1.0067  1.6736 
Country                      0.1562  2.2900   0.0682  0.9456  -4.3321  4.6445 
`NOS score`                 -0.0153  0.2529  -0.0603  0.9519  -0.5110  0.4805 
                             
intrcpt                      
`Neutral toys`               
factor(`Parent present`)2    
factor(`Parent present`)3    
factor(Setting)2             
factor(Setting)3             
Country                      
`NOS score`                  

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_female_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 26; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
-14.2104   28.4209   46.4209   54.4342   68.9209   

tau^2 (estimated amount of residual heterogeneity):     0.1677 (SE = 0.0878)
tau (square root of estimated tau^2 value):             0.4096
I^2 (residual heterogeneity / unaccounted variability): 67.16%
H^2 (unaccounted variability / sampling variability):   3.05
R^2 (amount of heterogeneity accounted for):            28.12%

Test for Residual Heterogeneity:
QE(df = 18) = 49.1231, p-val = 0.0001

Test of Moderators (coefficients 2:8):
QM(df = 7) = 14.0064, p-val = 0.0511

Model Results:

                           estimate      se     zval    pval    ci.lb   ci.ub 
intrcpt                     -2.4015  1.5137  -1.5865  0.1126  -5.3683  0.5654 
`Neutral toys`               1.1232  0.5081   2.2106  0.0271   0.1273  2.1191 
factor(`Parent present`)2    0.3935  0.3695   1.0650  0.2869  -0.3307  1.1177 
factor(`Parent present`)3    0.4243  0.3767   1.1266  0.2599  -0.3139  1.1625 
factor(Setting)2            -0.2322  0.3050  -0.7612  0.4465  -0.8299  0.3656 
factor(Setting)3             0.4290  0.5523   0.7768  0.4373  -0.6534  1.5115 
Country                      0.3710  1.7900   0.2072  0.8358  -3.1375  3.8794 
`NOS score`                  0.0399  0.1971   0.2023  0.8397  -0.3465  0.4262 
                             
intrcpt                      
`Neutral toys`             * 
factor(`Parent present`)2    
factor(`Parent present`)3    
factor(Setting)2             
factor(Setting)3             
Country                      
`NOS score`                  

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create author-team gender composition variable</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">author_gender =</span> <span class="fu">case_when</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Female authors</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="st">`</span><span class="at">Male authors</span><span class="st">`</span> <span class="sc">~</span> <span class="st">"Female-dominated"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Male authors</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="st">`</span><span class="at">Female authors</span><span class="st">`</span> <span class="sc">~</span> <span class="st">"Male-dominated"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Balanced"</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Code author-team gender composition (already added earlier)</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Meta-regression on author gender for male-typed preference</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>res_gender_male <span class="ot">&lt;-</span> <span class="fu">rma</span>(yi_m, vi_m, <span class="at">mods =</span> <span class="sc">~</span> <span class="fu">factor</span>(author_gender), <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_gender_male)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 27; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
-20.9136   41.8273   49.8273   54.5395   51.9326   

tau^2 (estimated amount of residual heterogeneity):     0.1964 (SE = 0.0835)
tau (square root of estimated tau^2 value):             0.4432
I^2 (residual heterogeneity / unaccounted variability): 72.35%
H^2 (unaccounted variability / sampling variability):   3.62
R^2 (amount of heterogeneity accounted for):            18.67%

Test for Residual Heterogeneity:
QE(df = 24) = 75.0792, p-val &lt; .0001

Test of Moderators (coefficients 2:3):
QM(df = 2) = 6.3170, p-val = 0.0425

Model Results:

                                       estimate      se     zval    pval 
intrcpt                                  1.6740  0.3448   4.8554  &lt;.0001 
factor(author_gender)Female-dominated   -0.7717  0.3625  -2.1287  0.0333 
factor(author_gender)Male-dominated      0.1521  0.7156   0.2126  0.8317 
                                         ci.lb    ci.ub      
intrcpt                                 0.9982   2.3497  *** 
factor(author_gender)Female-dominated  -1.4822  -0.0612    * 
factor(author_gender)Male-dominated    -1.2505   1.5547      

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Meta-regression on author gender for female-typed preference</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>res_gender_female <span class="ot">&lt;-</span> <span class="fu">rma</span>(yi_f, vi_f, <span class="at">mods =</span> <span class="sc">~</span> <span class="fu">factor</span>(author_gender), <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res_gender_female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 27; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
-22.1443   44.2887   52.2887   57.0009   54.3940   

tau^2 (estimated amount of residual heterogeneity):     0.2472 (SE = 0.0981)
tau (square root of estimated tau^2 value):             0.4972
I^2 (residual heterogeneity / unaccounted variability): 76.99%
H^2 (unaccounted variability / sampling variability):   4.35
R^2 (amount of heterogeneity accounted for):            1.63%

Test for Residual Heterogeneity:
QE(df = 24) = 87.3704, p-val &lt; .0001

Test of Moderators (coefficients 2:3):
QM(df = 2) = 2.0085, p-val = 0.3663

Model Results:

                                       estimate      se     zval    pval 
intrcpt                                 -1.1022  0.3521  -3.1300  0.0017 
factor(author_gender)Female-dominated    0.2580  0.3726   0.6925  0.4886 
factor(author_gender)Male-dominated     -0.5979  0.7480  -0.7993  0.4241 
                                         ci.lb    ci.ub     
intrcpt                                -1.7924  -0.4120  ** 
factor(author_gender)Female-dominated  -0.4722   0.9882     
factor(author_gender)Male-dominated    -2.0640   0.8682     

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forest plot for male-typed toys by author gender</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(res_male,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">slab =</span> data<span class="sc">$</span>Study,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">order =</span> data<span class="sc">$</span>author_gender,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">ilab =</span> data<span class="sc">$</span>author_gender,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">ilab.xpos =</span> <span class="sc">-</span><span class="dv">2</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">"Male‑Typed Toys by Author Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment_files/figure-html/author-gender-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<p><strong>Conclusions</strong></p>
<ol type="1">
<li><p><em>Pooled effect sizes</em>:</p>
<ul>
<li><strong>Male‑typed toys</strong>: Hedges’ g = 1.01 (95 % CI [0.79, 1.23]); boys spend substantially more time with these toys (p &lt; 0.001).</li>
<li><strong>Female‑typed toys</strong>: Hedges’ g = −0.90 (95 % CI [−1.12, −0.67]); girls prefer these toys over boys (p &lt; 0.001).</li>
</ul></li>
<li><p><em>Small‑study effects</em> (Egger’s tests):</p>
<ul>
<li>Male‑typed toys: z = 4.87, p &lt; 0.001 → pronounced funnel asymmetry.</li>
<li>Female‑typed toys: z = −3.30, p = 0.001 → significant asymmetry in the opposite direction.</li>
</ul></li>
<li><p><em>Methodological moderators</em> (meta‑regression):</p>
<ul>
<li><strong>Neutral toy inclusion</strong>: Excluding neutral toys amplifies sex differences for female‑typed toys (β = 1.12, p = 0.027). For male‑typed toys, the same covariate and other design factors (parental presence, setting, country GII, NOS score) were not significant (all p &gt; 0.10).</li>
<li>No additional moderators were significant for female‑typed toys beyond neutral‑toy status.</li>
</ul></li>
<li><p><em>Author‑gender composition</em>:</p>
<ul>
<li>Male‑typed toys: studies led by predominantly female teams reported smaller boy‑toy differences (β = −0.77, p = 0.033) than male‑led teams.</li>
<li>Female‑typed toys: author‑gender composition did <strong>not</strong> significantly influence reported girl‑toy differences (all p &gt; 0.20).</li>
</ul></li>
</ol>
<p>Overall, robust sex‑specific toy preferences emerge across studies; however, evidence of publication bias and limited moderator effects suggest future research should focus on preregistered protocols and balanced reporting to clarify true effect magnitudes.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>